Modified the 'type' of variable service_log_config and service_vpc_co…
terraform-alicloud-modules/terraform-alicloud-fc pull request #10
Opened 2022-01-25 09:47 UTC by MrWolong

…nfig

2022-04-07 07:52 UTC, xiaozhu36 requested changes

2022-04-07 07:52 UTC, xiaozhu36 commented on locals.tf
> +  count       = var.create_event_function ? 1 : 0
data 上不需要使用 count

2022-04-07 07:52 UTC, xiaozhu36 commented on outputs.tf
> +  value = length(alicloud_fc_service.this) > 0 ? alicloud_fc_service.this.0.name : ""
这个不用改吧

2022-04-07 08:08 UTC, MrWolong commented on locals.tf
> +  count       = var.create_event_function ? 1 : 0
这个如果不用count控制的话，会触发流控

2022-04-07 08:27 UTC, MrWolong commented on outputs.tf
> +  value = length(alicloud_fc_service.this) > 0 ? alicloud_fc_service.this.0.name : ""
![image](https://user-images.githubusercontent.com/36806235/162155312-44b73fb3-266b-47ed-8751-2999799fe9aa.png)
![image](https://user-images.githubusercontent.com/36806235/162155345-c5bb5e69-3fb5-4565-a0c7-384bfcd88268.png)
如果使用local.service_name，会报service不存在

2022-04-07 09:34 UTC, xiaozhu36 requested changes

2022-04-07 09:34 UTC, xiaozhu36 commented on locals.tf
> +  count       = var.create_event_function ? 1 : 0
如果有流控，那么需要在 provider 中针对流控错误增加相应的重试逻辑

2022-04-18 02:36 UTC, xiaozhu36 requested changes

2022-04-18 02:36 UTC, xiaozhu36 commented on outputs.tf
> +  value = length(alicloud_fc_service.this) > 0 ? alicloud_fc_service.this.0.name : ""
现在既然local 已经改了，那么直接使用 local.service_name 应该就可以啊

2022-04-18 10:18 UTC, MrWolong commented on outputs.tf
> +  value = length(alicloud_fc_service.this) > 0 ? alicloud_fc_service.this.0.name : ""
已修改

2022-04-18 10:19 UTC, MrWolong commented on outputs.tf
> +  value = length(alicloud_fc_service.this) > 0 ? alicloud_fc_service.this.0.name : ""
已修改

2022-04-19 02:28 UTC, merged